/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Hiago Tadeu (https://sketchfab.com/hdragneel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sniper-rifle-53c25fd058e6468693f9227c6cae8686
title: Sniper Rifle
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model({...props}) {
  const group = useRef()
  const {nodes, materials} = useGLTF('/gun4.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI, Math.PI / 2, 0]} scale={100}>
            <mesh
              geometry={nodes['Cylinder_Metal_Semi-Brilhante_escuro_0'].geometry}
              material={materials['Metal_Semi-Brilhante_escuro']}
            />
            <mesh geometry={nodes.Cylinder_Metal_Fosco_0.geometry} material={materials.Metal_Fosco} />
            <mesh geometry={nodes.Cylinder_Metal_Brilhante_0.geometry} material={materials.Metal_Brilhante} />
            <mesh geometry={nodes['Cylinder_Muni��ao_0'].geometry} material={materials.Muniao} />
            <mesh
              geometry={nodes['Cylinder_Pe��as_Cilindricas_Pequenas_0'].geometry}
              material={materials.Peas_Cilindricas_Pequenas}
            />
            <mesh geometry={nodes.Cylinder_Scope_0.geometry} material={materials.Scope} />
            <mesh geometry={nodes.Cylinder_Lentes_0.geometry} material={materials.Lentes} />
            <mesh geometry={nodes.Cylinder_Gatilho_0.geometry} material={materials.Gatilho} />
            <mesh geometry={nodes.Cylinder_Ajustador_0.geometry} material={materials.Ajustador} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gun4.gltf')
