/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DMaesen (https://sketchfab.com/bumstrum)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sniper-3-ece457b5c8bb475ba2236b00b29c55a8
title: Sniper 3
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model({...props}) {
  const group = useRef()
  const {nodes, materials} = useGLTF('/gun3.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -0.31]}>
            <group position={[0, 0, 0.31]}>
              <mesh geometry={nodes.base_sniper_0.geometry} material={nodes.base_sniper_0.material} />
            </group>
            <group position={[-1.45, 8.6, 0.33]}>
              <mesh geometry={nodes.boltlid_sniper_0.geometry} material={nodes.boltlid_sniper_0.material} />
            </group>
            <group position={[0, 8.6, 8.58]}>
              <mesh geometry={nodes.bolt_sniper_0.geometry} material={nodes.bolt_sniper_0.material} />
            </group>
            <group position={[0, 12.01, 0.71]}>
              <group position={[0, 0.91, 45.21]}>
                <mesh geometry={nodes.front_sniper_0.geometry} material={nodes.front_sniper_0.material} />
              </group>
              <group position={[0, 0.42, -1.06]}>
                <mesh geometry={nodes.rear_sniper_0.geometry} material={nodes.rear_sniper_0.material} />
              </group>
              <mesh geometry={nodes.sights_sniper_0.geometry} material={nodes.sights_sniper_0.material} />
            </group>
            <group position={[0, 15.39, 13.88]}>
              <mesh geometry={nodes.scope_sniper_0.geometry} material={nodes.scope_sniper_0.material} />
            </group>
            <group position={[0, 3.95, 4.9]}>
              <mesh geometry={nodes.trigger_sniper_0.geometry} material={nodes.trigger_sniper_0.material} />
            </group>
            <group position={[0, 0.19, 10.62]}>
              <mesh geometry={nodes.magrelease_sniper_0.geometry} material={nodes.magrelease_sniper_0.material} />
            </group>
            <group position={[0, 3.23, 16.51]}>
              <group position={[0, 3.2, -1.72]}>
                <mesh geometry={nodes.bullet_sniper_0.geometry} material={nodes.bullet_sniper_0.material} />
              </group>
              <mesh geometry={nodes.magazine_sniper_0.geometry} material={nodes.magazine_sniper_0.material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gun3.gltf')
