/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DMaesen (https://sketchfab.com/bumstrum)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sniper-cdefd833b4b5407ba32c53c9e7f50cae
title: Sniper
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model({...props}) {
  const group = useRef()
  const {nodes, materials} = useGLTF('/gun2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.base_sniper_0.geometry} material={nodes.base_sniper_0.material} />
          <group position={[0, 18.9, 24.26]}>
            <mesh geometry={nodes.scope_sniper_0.geometry} material={nodes.scope_sniper_0.material} />
          </group>
          <group position={[0, 11.12, 5.57]}>
            <group position={[0, 0, 6.18]}>
              <mesh geometry={nodes.bolt_sniper_0.geometry} material={nodes.bolt_sniper_0.material} />
            </group>
            <mesh geometry={nodes.boltback_sniper_0.geometry} material={nodes.boltback_sniper_0.material} />
          </group>
          <group position={[0, 3.28, 13.19]}>
            <mesh geometry={nodes.release_sniper_0.geometry} material={nodes.release_sniper_0.material} />
          </group>
          <group position={[0, 4.54, 7.63]}>
            <mesh geometry={nodes.trigger_sniper_0.geometry} material={nodes.trigger_sniper_0.material} />
          </group>
          <group position={[0, 2.78, 19.48]}>
            <group position={[0, 5.53, -0.08]}>
              <mesh geometry={nodes.bullet_sniper_0.geometry} material={nodes.bullet_sniper_0.material} />
            </group>
            <mesh geometry={nodes.mag_sniper_0.geometry} material={nodes.mag_sniper_0.material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gun2.gltf')
