/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3DHaupt (https://sketchfab.com/dennish2010)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/ksr-29-sniper-jEosSrePMDJR9GXwpALOOaRkT3E
title: KSR 29 Sniper
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'

export default function Model({...props}) {
  const group = useRef()
  const {nodes, materials} = useGLTF('/gun1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.03, 0, 1.41]} rotation={[0, -0.09, 0]}>
          <mesh geometry={nodes.Cube_0.geometry} material={materials['Material.003']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gun1.gltf')
